In [1]:
import zeus

In [2]:

import LazyEval
import allshowers
import numpy as np
import matplotlib.pyplot as plt
import showerdata
import zarr

In [3]:
import h5py as h5
import time

In [4]:
data_conditioning = "/data/dust/user/diptarko/data/showers.h5"

In [5]:
file = h5.File(data_conditioning, "r")

In [6]:
file["showers"][5]

array([-3.6136116e+01, -3.5260704e+01,  1.9000000e+01, ...,
       -7.4566779e+02,  7.7000000e+01,  1.4164904e-05],
      shape=(7076,), dtype=float32)

In [7]:
# x = []
# y = []
# for i in [1,5,10,20,50,100,200,500,1_000,2_000,5_000,10_000,20_000,50_000,100_000,200_000,500_000]:
#     time_start = time.time()

#     showers_all = showerdata.load(data_conditioning,
#                                 stop=i
#                                 )
#     time_end = time.time()
#     x.append(i)
#     y.append(time_end - time_start)
#     print(f"Time taken to load {i} showers: {time_end - time_start} seconds")

In [19]:
showers_all = showerdata.load(data_conditioning,
                              # start=2,
                            stop=100)

In [24]:
showers_all_zeus = list([zeus.ZeusArray.create_zeus_array(showers_all.points[i]) for i in range(showers_all.points.shape[0])])

In [25]:
from zeus.core import dataset
z_data = dataset.ZeusShard.CreateZeusShardFromList(showers_all_zeus)

In [26]:
shard_data = dataset.ZeusShard.compress(z_data,clevel=5)
# shard_data = z_data

In [27]:
zeus.io.writer.writeshard(shard_data=shard_data,path="./example.zeus")

In [28]:
path = "./example.zeus"

In [29]:
read_shard = zeus.io.reader.readshard(path=path)

In [30]:
read_shard.data_block.data == shard_data.data_block.data

True

In [28]:
shard_data.data_block.data

array([-1.3393218e+01,  4.1688442e+01,  1.0000000e+00, ...,
       -4.6949423e+02,  7.7000000e+01,  1.1175159e-05],
      shape=(1052303,), dtype=float32)

In [27]:
read_shard.data_block.offsets == shard_data.data_block.offsets

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [17]:
read_shard.data_block.offsets

array([  18602,   49533,   79291,  105022,  119225,  139101,  186075,
        214976,  220604,  237255,  284243,  308176,  364353,  401324,
        432511,  471063,  473897,  521618,  558477,  598929,  613461,
        660339,  696572,  719445,  762796,  793856,  832287,  850392,
        872453,  912588,  954413,  958885, 1007810, 1049388, 1098902,
       1138078, 1143888, 1188421, 1237884, 1277709, 1298187, 1331076,
       1344081, 1390142, 1428186, 1465706, 1479312, 1488488, 1499531,
       1518066, 1557672, 1576427, 1588826, 1623065, 1661097, 1699890,
       1704030, 1731662, 1761815, 1813309, 1852283, 1883887, 1909359,
       1945302, 1975166, 2008930, 2035811, 2048080, 2071617, 2099801,
       2131489, 2154798, 2201319, 2225450, 2250685, 2254980, 2298821,
       2322246, 2364745, 2375943, 2426026, 2458916, 2502192, 2521118,
       2533395, 2574319, 2579212, 2599596, 2644601, 2697254, 2722974,
       2763819, 2772845, 2822910, 2851756, 2863896, 2867601, 2890746,
       2931088, 2959